repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: .pre-commit/check-tests.sh
        language: script
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: .pre-commit/check-lint.sh
        language: script
        pass_filenames: false

