name: Continuous Integration

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    uses: ./.github/workflows/lint-test.yml