name: Security

on: push

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute safety
        run: |
          safety